---
extends:
  airbnb

env:
  browser: true
  es6: true
  jest: true

installedESLint: true

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

globals:
  ENV: false
  chrome: false

rules:
  arrow-parens:
    - error
    - as-needed
  import/no-named-as-default:
    - off
  import/extensions:
    - error
    - never
  new-cap:
    - error
    - capIsNewExceptions:
      - List
      - DragSource
      - DropTarget
      - DragDropContext
      - Map
  react/jsx-filename-extension:
    - error
    - extensions:
      - .js

settings:
  import/resolver:
    webpack:
      config: 'dev/webpack/webpack.config.js'

